[package]
name = "linux-fleet-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ssh2 = "0.10"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
