[package]
name = "linux-fleet-manager"
version = "0.2.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ssh2 = "0.9.4"
toml = "0.7.3"
serde = "1.0"
serde_derive = "1.0"
indicatif = "0.17.3"
futures = "0.3"